# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-12-04 07:25
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('logic', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Hero',
            fields=[
                ('name', models.CharField(max_length=64)),
                ('hero_id', models.IntegerField(primary_key=True, serialize=False)),
                ('localized_name', models.CharField(max_length=64)),
                ('url_small_portrait', models.URLField(default='')),
                ('url_large_portrait', models.URLField(default='')),
                ('url_full_portrait', models.URLField(default='')),
                ('url_vertical_portrait', models.URLField(default='')),
            ],
        ),
        migrations.CreateModel(
            name='Matches',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('match_id', models.IntegerField(db_index=True, unique=True)),
                ('match_seq_num', models.IntegerField(db_index=True)),
                ('start_time', models.FloatField(db_index=True)),
                ('series_id', models.IntegerField()),
                ('series_type', models.SmallIntegerField(choices=[(0, 'Non-series'), (1, 'BO3'), (1, 'BO5')], default=0)),
                ('players', models.TextField()),
                ('dire_team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dire_team', to='logic.Club')),
                ('league', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='logic.League')),
                ('lobby_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='logic.LobbyType')),
                ('radiant_team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='radiant_team', to='logic.Club')),
            ],
        ),
        migrations.CreateModel(
            name='MatchToPlayer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('player_slot', models.IntegerField()),
                ('hero_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='logic.Hero')),
                ('match_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='logic.Matches', to_field='match_id')),
            ],
        ),
        migrations.RemoveField(
            model_name='leaguematches',
            name='dire_team',
        ),
        migrations.RemoveField(
            model_name='leaguematches',
            name='league',
        ),
        migrations.RemoveField(
            model_name='leaguematches',
            name='lobby_type',
        ),
        migrations.RemoveField(
            model_name='leaguematches',
            name='radiant_team',
        ),
        migrations.RemoveField(
            model_name='players',
            name='id',
        ),
        migrations.AddField(
            model_name='players',
            name='avatar',
            field=models.URLField(default=''),
        ),
        migrations.AddField(
            model_name='players',
            name='avatarfull',
            field=models.URLField(default=''),
        ),
        migrations.AddField(
            model_name='players',
            name='avatarmedium',
            field=models.URLField(default=''),
        ),
        migrations.AddField(
            model_name='players',
            name='club',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='logic.Club'),
        ),
        migrations.AddField(
            model_name='players',
            name='communityvisibilitystate',
            field=models.SmallIntegerField(default=1),
        ),
        migrations.AddField(
            model_name='players',
            name='is_admin',
            field=models.SmallIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='players',
            name='lastlogoff',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='players',
            name='personaname',
            field=models.CharField(default='', max_length=256),
        ),
        migrations.AddField(
            model_name='players',
            name='personastate',
            field=models.SmallIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='players',
            name='personastateflags',
            field=models.SmallIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='players',
            name='primaryclanid',
            field=models.CharField(default='', max_length=64),
        ),
        migrations.AddField(
            model_name='players',
            name='profilestate',
            field=models.SmallIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='players',
            name='profileurl',
            field=models.URLField(default=''),
        ),
        migrations.AddField(
            model_name='players',
            name='steamid',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='players',
            name='timecreated',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='players',
            name='account_id',
            field=models.IntegerField(db_index=True, primary_key=True, serialize=False, unique=True),
        ),
        migrations.DeleteModel(
            name='LeagueMatches',
        ),
        migrations.AddField(
            model_name='matchtoplayer',
            name='player_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='logic.Players'),
        ),
        migrations.AlterUniqueTogether(
            name='matchtoplayer',
            unique_together=set([('player_id', 'match_id')]),
        ),
    ]
