# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-12-15 06:27
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('logic', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='matches',
            name='match_id',
            field=models.BigIntegerField(db_index=True, unique=True),
        ),
    ]
