# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-12-04 07:38
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('logic', '0002_auto_20171204_1525'),
    ]

    operations = [
        migrations.RenameField(
            model_name='hero',
            old_name='hero_id',
            new_name='id',
        ),
    ]
