# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-12-04 09:52
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('logic', '0005_players_commentpermission'),
    ]

    operations = [
        migrations.AddField(
            model_name='players',
            name='realname',
            field=models.CharField(max_length=128, null=True),
        ),
    ]
